steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  id: 'build'
  args:
  - '-c'
  - |
    echo "Here's a convenient pattern to use for embedding shell scripts in cloudbuild.yaml."
    echo "This step only builds an image if this build was triggered by a push to master."
    echo "{\"gitsha\": \"$COMMIT_SHA\"}" > devops-demo/info.json
    docker build -t gcr.io/$PROJECT_ID/node-demo:$COMMIT_SHA .
    [[ "$BRANCH_NAME" == "master" ]] && docker tag gcr.io/$PROJECT_ID/node-demo:$COMMIT_SHA gcr.io/$PROJECT_ID/node-demo:prod-$COMMIT_SHA || exit 0
    
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  id: 'push'
  args:
  - '-c'
  - |
    docker push gcr.io/$PROJECT_ID/node-demo:$COMMIT_SHA
    [[ "$BRANCH_NAME" == "master" ]] && docker push gcr.io/$PROJECT_ID/node-demo:prod-$COMMIT_SHA || exit 0

- name: 'gcr.io/devops-hof/fluxctl'
  id: 'fluxctl'
  env:   
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=devops-hof-demo'
  - 'USER=fluxctl'
  - 'FLUX_FORWARD_NAMESPACE=flux'
  - 'CONTROLLER=default:deployment/devops-demo-staging'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo $USER

#